# Game Configuration Constants
# All hardcoded values centralized here for easy modification

# Game Information
VERSION = "0.1.5"
LAUNCH_DATE = "2025/07/13"

# Development Settings
DEBUG = False

# Window Settings
WIN_WIDTH = 128
WIN_HEIGHT = 128
DISPLAY_SCALE = 5
FPS = 60

# Sprite Banks
TILE_BANK0 = 0
TILE_BANK1 = 1
TILE_BANK2 = 2

# Game State Constants
STATE_TITLE = 0
STATE_PLAYING = 1
STATE_GAMEOVER = 2
STATE_PAUSE = 3
STATE_GAMECLEAR = 4

# Playing Sub-States
STATE_PLAYING_ENEMY_ENTRY = 0
STATE_PLAYING_ENEMY_SPAWN = 1
STATE_PLAYING_FIGHT = 2
STATE_PLAYING_STAGE_CLEAR = 3

# Stage Management
MAX_STAGE = 4

# Visual Effects
STOP_TIME = 20
SHAKE_TIME = 10
SHAKE_STRENGTH = 10

# Player Settings
PLAYER_SPEED = 1
PLAYER_SHOT_INTERVAL = 16
PLAYER_EXPLODE_TIMER = 180
PLAYER_COLLISION_BOX = (2, 2, 4, 4)  # x, y, w, h

# Bullet Settings
BULLET_SPEED = 3
BULLET_COLLISION_BOX = (2, 2, 4, 4)  # x, y, w, h

# Enemy Bullet Settings
ENEMY_BULLET_SPEED = 2
ENEMY_BULLET_COLLISION_BOX = (2, 2, 4, 4)  # x, y, w, h

# Enemy Settings
ENEMY_MOVE_SPEED = 0.5
ENEMY_MOVE_THRESHOLD = 1
ENEMY_SHOOT_INTERVAL = 60
ENEMY_BASE_SHOOT_CHANCE = 0.10
ENEMY_MAX_SHOOT_CHANCE = 0.30
ENEMY_ANIM_FRAME = 10
ENEMY_COLLISION_BOX = (1, 1, 6, 6)  # x, y, w, h

# Enemy Attack System
PREPARE_ATTACK_DURATION = 60
PREPARE_SHAKE_AMPLITUDE_X = 1.0
PREPARE_SHAKE_AMPLITUDE_Y = 1.2
PREPARE_SHAKE_FREQUENCY_X = 0.2
PREPARE_SHAKE_FREQUENCY_Y = 1.0

ATTACK_MOVE_SPEED = 0.8
ATTACK_SWAY_AMPLITUDE = 1.5
ATTACK_SWAY_FREQUENCY = 0.08
RETURN_DELAY = 180
RETURN_DELAY_CONTINUOUS = 60
DESCEND_SPEED = 1.5
FORMATION_PROXIMITY = 8
ATTACK_COOLDOWN = 300

# Enemy AI Settings
ATTACK_SELECTION_INTERVAL = 240
ATTACK_CHANCE = 0.75

# Star Field Settings
STAR_COUNT = 100
STAR_SPEED = 0.5

# Explosion Settings
EXPLOSION_PARTICLE_COUNT = 20
EXPLOSION_PARTICLE_SPEED = 3
EXPLOSION_DURATION = 60

# Audio Settings
AUDIO_CHANNEL_PLAYER = 0
AUDIO_CHANNEL_ENEMY = 0
AUDIO_CHANNEL_EXPLOSION = 0